# 后端配置
server:
  port: 1314
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /lvxz

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: src/main/resources
  http:
    encoding:
      force: false
      charset: UTF-8
      enabled: true

  messages:
    encoding: UTF-8

  mvc:
    static-path-pattern: /**
  thymeleaf:
    cache: true
    prefix: classpath:/templates/ #对文件夹进行拦截
    suffic: .html                 #对文件格式进行限制
    mode: HTML5
    encoding: UTF-8

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/selection?characterEncoding=utf8&useSSL=true
    username: root
    password: 12345678

mybatis:
  mapper-locations: classpath:mybatis/dao/*.xml
  type-aliases-package: com.njfu.selection.entity
  configuration:
    mapUnderscoreToCamelCase: true
    useColumnLabel: true

redis:
  host: 127.0.0.1
  port: 6379
  timeout: 3
  poolMaxTotal: 10
  poolMaxIdle: 10
  poolMaxWait: 3

logging:
  config: classpath:logback.xml





  # 后端配置获取常量配置
message:

  mysql_error:
    code: -9
    msg: 数据库操作发生错误，等待恢复


  login:
    success:
      msg: 登录成功
    failure_1:
      msg: 登录失败，密码存在错误，请重新输入
    failure_2:
      msg: 登录失败，用户不存在
    failure_3:
      msg: 登录失败，你的账户已被冻结

  add:
    success:
      msg: 添加成功
    failure:
      msg: 添加失败，账号已存在

  update:
    password:
      success:
        msg: 更新密码成功
      failure_1:
        msg: 更新密码失败，用户不存在
      failure_2:
        msg: 更新密码失败，原密码错误
      failure_3:
        msg: 更新密码失败，输入验证资料有误
    info:
      success:
        msg: 更新信息成功
      failure:
        msg: 更新信息失败，用户不存在

  enable:
    success_1:
      msg: 冻结成功
    failure_1:
      msg: 解冻失败
    success_2:
      msg: 解冻成功
    failure_2:
      msg: 解冻失败


  file:
    upload:
      success:
        msg: 上传成功
      failure_1:
        msg: 上传失败，
      failure_2:
        msg: 上传失败，文件为空
      failure_3:
        msg: 上传失败，文件不存在
      failure_4:
        msg: 上传失败，老师账号不存在
      failure_5:
        msg: 上传失败，学生账号不存在
      failure_6:
        msg: 上传失败，执行dao错误

  design:
    update:
      success_1:
        msg: 确定通过成功
      failure_1:
        msg: 确定通过失败，申请已经不存在
      success_2:
        msg: 驳回申请成功
      failure_2:
        msg: 驳回申请失败，申请已经不存在

      success_3:
        msg: 正式发布成功
      failure_3:
        msg: 正式发布失败，申请已经不存在

      success_4:
        msg: 禁止选择成功
      failure_4:
        msg: 禁止选择失败

      success_5:
        msg: 完结毕设成功
      failure_5:
        msg: 完结毕设失败

    delete:
      success:
        msg: 删除毕设成功
      failure_1:
        msg: 删除毕设失败


  project:
    insert:
      success:
        msg: 申请毕设操作成功
      failure_1:
        msg: 申请毕设操作失败，教师自己没有发布毕设
      failure_2:
        msg: 申请毕设操作失败，你的毕设已存在
      failure_3:
        msg: 申请毕设操作失败，毕设信息已不存在或者已不在当前正式发布下
    delete:
      success:
        msg: 删除申请成功
      failure:
        msg: 删除申请失败，操作存在错误
    select:
      success:
        msg: 学生毕设信息已接收
      failure:
        msg: 学生没有毕设项目信息
    update:
      success_1:
        msg: 确定通过成功
      failure_1:
        msg: 确定通过失败，申请已经不存在
      success_2:
        msg: 驳回申请成功
      failure_2:
        msg: 驳回申请失败，申请已经不存在

  help:
    teacher:
      success:
        msg: 教师自己毕设信息已接收
      success_1:
        msg: 学生申请毕设信息已接收
      failure:
        msg: 教师自己没有毕设信息
      failure_1:
        msg: 没有学生申请毕设信息

    admin:
      success:
        msg: 教师毕设信息已接收
      failure_1:
        msg: 教师没有毕设申请信息
      failure_2:
        msg: 管理员不存在

    student:
      success:
        msg: 教师毕设信息已接收
      failure_1:
        msg: 教师没有毕设发布信息
      failure_2:
        msg: 学生不存在
